#!/usr/bin/env python3
import os
import subprocess
from sys import platform

ROOT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_PATH = os.path.join(ROOT_DIR, ".bazelrc")


def run_cmd(cmd):
    try:
        output = subprocess.check_output(
            cmd.split(" "), stderr=subprocess.STDOUT
        ).decode()
    except subprocess.CalledProcessError as e:
        output = e.output.decode()
        raise RuntimeError(output)
    return output.rstrip()


def main():
    with open(OUT_PATH, "w") as f:
        # TODO: add ubsan + msan builds also
        f.write(
            """
build --cxxopt="-std=c++14"
build --cxxopt="-Wall"
# ASAN build
# TODO: add ubsan + msan builds also
build:asan --strip=never
build:asan --copt -fsanitize=address
build:asan --copt -DADDRESS_SANITIZER
build:asan --copt -O1
build:asan --copt -g
build:asan --copt -fno-omit-frame-pointer
build:asan --linkopt -fsanitize=address
"""
        )

        # MacOS
        if platform == "darwin":
            # get canonical brew path
            conda_prefix = os.environ["CONDA_PREFIX"]
            conda_bin = os.path.join(conda_prefix, "bin")
            conda_inc = os.path.join(conda_prefix, "include")
            conda_lib = os.path.join(conda_prefix, "lib")

            # get canonical omp path
            sdk_path = run_cmd("xcrun --sdk macosx --show-sdk-path")
            
            # get omp path
            omp_prefix = run_cmd("brew --prefix libomp")
            omp_path = os.path.join(omp_prefix, "lib")
            f.write(
                f"""
# Use clang from conda-forge
#build --action_env=CC={conda_bin}/clang
#build --action_env=CXX={conda_bin}/clang++
#build --action_env=BAZEL_CXXOPTS=-isystem{conda_inc}
#build --action_env=BAZEL_LINKOPTS=-L{conda_lib}:-Wl,-rpath,{conda_lib}
#build --cxxopt -Xclang 
build --action_env=SDKROOT={sdk_path}
build --cxxopt -fopenmp
build --linkopt -L{omp_path}
build --linkopt -lomp
# Tell Bazel not to use the full Xcode toolchain on Mac OS
build --repo_env=BAZEL_USE_CPP_ONLY_TOOLCHAIN=1
build:gcc --action_env=CC=gcc-11
build:gcc --action_env=CXX=g++-11"""
            )
        else:
            # Linux
            f.write(
                """
# Linux Clang
build --cxxopt -fopenmp
build --linkopt -fopenmp
build:clang --action_env=CC=clang
build:clang --action_env=CXX=clang++
# Linux GCC (default)
build --action_env=CC=gcc
build --action_env=CXX=g++
"""
            )


if __name__ == "__main__":
    main()