# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Solves the solution for the equation (w.r.t. \f$x\f$):
#' \f[
#'      minimize \frac{1}{2} x^\top L x - x^\top v 
#'          + l_1 ||x||_2 + \frac{l_2}{2} ||x||_2^2
#' \f]
#'      
#' @param   L       vector representing a diagonal PSD matrix.
#'                  Must have max(L + s) > 0. 
#'                  L.size() <= buffer1.size().
#' @param   v       any vector.  
#' @param   l1      L2-norm penalty. Must be >= 0.
#' @param   l2      L2 penalty. Must be >= 0.
#' @param   tol         Newton's method tolerance of closeness to 0.
#' @param   max_iters   maximum number of iterations of Newton's method.
#' @param   x           solution vector.
#' @param   iters       number of Newton's method iterations taken.
#' @param   buffer1     any vector with L.size() <= buffer1.size().
#' @param   buffer2     any vector with L.size() <= buffer2.size().
#' @export
newton_solver <- function(L, v, l1, l2, tol, max_iters) {
    .Call(`_glstudy_newton_solver`, L, v, l1, l2, tol, max_iters)
}

#' Computes the group-lasso objective.
#' 
#' @param   A       any square (p, p) matrix. 
#' @param   r       any vector (p,).
#' @param   groups  vector defining group beginning indices.
#' @param   group_sizes vector defining group sizes.
#' @param   alpha       elastic net proportion.
#' @param   penalty penalty factor for each group.
#' @param   lmda    group-lasso regularization.
#' @param   beta    coefficient vector.
#' @export
objective <- function(A, r, groups, group_sizes, alpha, penalty, lmda, beta) {
    .Call(`_glstudy_objective`, A, r, groups, group_sizes, alpha, penalty, lmda, beta)
}

