name: Build, Test, and Document

on:
  push:
    branches:    
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        # persist only for runs on this commit.
        cache-environment-key: environment-${{ github.sha }}
        cache-downloads-key: downloads-${{ github.sha }}
        init-shell: >-
          bash

  test:
    name: >-
      Test distribution
    needs:
    - build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        # persist only for runs on this commit.
        cache-environment-key: environment-${{ github.sha }}
        cache-downloads-key: downloads-${{ github.sha }}
        init-shell: >-
          bash
    - name: Set up dependencies
      run: |
        poetry install --without dev --no-root
    - name: Install Adelie
      run: pip install -e .
    - name: Move Mosek license
      run: 
        mkdir -p $HOME/mosek
        cp docs/mosek/mosek.lic $HOME/mosek
    - name: Run tests
      run: python3 -m pytest tests

  doc:
    name: >-
      Build documentation
    needs:
    - build
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    permissions:
      id-token: write  # IMPORTANT: mandatory for publishing

    steps:
    - uses: actions/checkout@v4
    - uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        # persist only for runs on this commit.
        cache-environment-key: environment-${{ github.sha }}
        cache-downloads-key: downloads-${{ github.sha }}
        init-shell: >-
          bash
    - name: Install Adelie
      run: pip install -e .
    - name: Install pandoc
      run: |
        sudo wget https://github.com/jgm/pandoc/releases/download/3.1.8/pandoc-3.1.8-1-amd64.deb -O /tmp/pandoc-3.1.8-1-amd64.deb
        sudo dpkg -i /tmp/pandoc-3.1.8-1-amd64.deb
    - name: Build documentation
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git checkout gh-pages
        git merge -X theirs origin/main
        cd docs
        rm -rf _images _sources _static .doctrees generated notebooks *.html *.inv *.js .buildinfo
        cd sphinx
        make clean && make html
        cp -r _build/html/* ..
        touch .nojekyll
    - name: Commit documentation changes
      run: |
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: docs
        github_token: ${{ secrets.ACTIONS_TOKEN }}
