name: Build Documentation

on:
  push:
    branches:    
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
        
    steps:
    - uses: actions/checkout@v1
    - uses: conda-incubator/setup-miniconda@v2
      with:
        mamba-version: "*"
        activate-environment: grpglmnet
        environment-file: environment.yml
        auto-activate-base: false
    - name: Set up dependencies
      run: |
        conda activate grpglmnet
        poetry install --only doc --no-root
    - name: Install grpglmnet
      run: |
        pip install -e .
    # Standard drop-in approach that should work for most people.
    - name: Build documentation
      run: |
        git checkout gh-pages
        git merge -X theirs origin/main
        cd docs
        sphinx-build sphinx html
        cd ..
    # Great extra actions to compose with:
    # Create an artifact of the html output.
    - uses: actions/upload-artifact@v1
      with:
        name: DocumentationHTML
        path: docs/html
    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit documentation changes
      run: |
        mv docs/html/* docs/
        rm -rf docs/html
        cd docs/
        touch .nojekyll
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update documentation" -a || true
        # The above command will fail if no changes were present, so we ignore
        # that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: docs
        github_token: ${{ secrets.ACTIONS_TOKEN }}
    # ===============================
